CREATE DATABASE IF NOT EXISTS registration_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE registration_app;

CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  student_name VARCHAR(100) NOT NULL,
  student_id VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
